// <auto-generated />
namespace api_data_bd.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Instituition : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Instituition));
        
        string IMigrationMetadata.Id
        {
            get { return "202008271546072_Instituition"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
